# Generated by Django 3.2.5 on 2021-10-01 17:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shopledgerapp', '0003_customerdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdata',
            name='id',
        ),
        migrations.AddField(
            model_name='customerdata',
            name='uu_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
