# Generated by Django 3.2.5 on 2021-10-01 17:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shopledgerapp', '0004_auto_20211001_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdata',
            name='uu_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
